# This workflow will build a Java project with Gradle

name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '8.0.302+8', '11.0.12+7', '16.0.2+7', '17.0.0+35' ]

    name: Test on Java ${{ matrix.Java }}

    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.Java }}
          check-latest: true

      - name: Build and Test
        run: |
          ./gradlew --version
          ./gradlew -Dbadass-jar-log-level=trace test --info
